<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_p</name>
   <tag></tag>
   <elementGuidId>76991ba5-d9a3-4c0e-af75-444d021b209f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ybar-sbq</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ybar-sbq']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a3810ee-c134-4c6a-9c75-93431aebf3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f31714a-1ebc-45ce-bb63-beb95fed2de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_yb_fsw74  _yb_ha1fz  </value>
      <webElementGuid>0c5457e7-8697-4576-875c-81f937fb7bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ybar-sbq</value>
      <webElementGuid>e2998137-1330-4b5b-ba71-137ae403890e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>303980b6-aad5-4e24-a931-45c7350c16f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>17f7ae38-ec2a-4dc4-a383-a563b87d18a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ylk</name>
      <type>Main</type>
      <value>sec:ybar;slk:websrch;subsec:searchbox;elm:search;elmt:input;itc:0;</value>
      <webElementGuid>d04b29cd-aff9-4205-82b8-9a4557881aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search the web</value>
      <webElementGuid>8d16fce1-51cb-41e3-a392-7e4d41984c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rapid_p</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>7661c849-348d-48f7-9983-d74b99a4307c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-v9y</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>64daffb6-0bb7-4f77-9852-b2b6c765c2ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f4f64f9e-8b88-4b9a-a4cf-2277ad8ef049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>both</value>
      <webElementGuid>7a78f718-8305-4240-81ae-63ab0b76cb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b96ea412-016a-4631-bd42-aba2b6651e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ybar-sbq&quot;)</value>
      <webElementGuid>e4afb55c-4af4-45ba-816e-95b754abfa0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ybar-sbq']</value>
      <webElementGuid>9d3cc926-ab4a-437c-a351-a2a6ec1213ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='ybar-sf']/input</value>
      <webElementGuid>79edcd22-d147-467f-8152-27b67349d3c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ce449a6a-b38f-499e-8c2c-d4b39fa0c144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ybar-sbq' and @name = 'p' and @placeholder = 'Search the web']</value>
      <webElementGuid>e9f8c54a-a518-4605-a8f7-36ebaf67cf66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
